services:
  mongo:
    image: "mongo"
    ports:
      - "8080:27017" #docker port: localmachine port you can fix docker port as your wish

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - "./backend/.env.prod"

  frontend:
    build: './frontend'
    ports:
      - "3000:3000"
    env_file:
      - "./frontend/.env.prod"