name: MERN CI

# trigger
on:
  push:
    branches: [main]
 
# works
jobs:
  mongo-init:
    runs-on: ubuntu-latest

    services:
      mongo:
          image: mongo
          ports: ['27017:27017']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Wait for MongoDB to be ready
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
          echo "MongoDB is up!"
      - name: Seed the MongoDB
        working-directory: ./backend
        run: |
          npm install
          node seedTasksData.js
  test:
    runs-on: ubuntu-latest
    needs: mongo-init # ensure mongo-init job is done before this

    env:
      PORT: ${{ secrets.PORT }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install
    
    - name: Run Backend tests
      working-directory: ./backend
      run: npm test

    
